widgets:
  -
    position: left
    type: profile
    author: K4LM3D
    author_title: Civilian
    location: Torn City
    avatar: /images/banners/K4LM3D_standard.gif
    avatar_rounded: true
    gravatar: 
    # follow_link: https://github.com/K4LM3D
    social_links:
      Facebook:
        icon: fab fa-facebook
        url: https://facebook.com/profile.php?id=100091224549821
      Instagram:
        icon: fab fa-instagram
        url: https://www.instagram.com/k4lm3d
      Twitter:
          icon: fab fa-twitter
          url: https://twitter.com/K4LM3D
      TikTok:
        icon: fab fa-tiktok
        url: https://tiktok.com/K4LM3D
  - 
    position: right
    type: toc
    index: true
  - position: right
    type: links
    links:
      Play Torn: https://www.torn.com
      Referral Link: https://www.torn.com/3091002
      My Bazaar: https://www.torn.com/bazaar.php?userId=3091002#/
      Course Checklist: /torn/course-checklist
  # -
  #   type: recent_posts
  #   position: left
  # -
  #   type: categories
  #   position: right
  # -
  #   type: tags
  #   position: right